name: Node CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
    - name: npm build and deploy
      run: |
        git config --global user.email "rvshiriev@gmail.com"
        git config --global user.name "shiriev"
        git remote set-url origin https://$TOKEN@github.com/shiriev/shiriev-2048.git
        npm run deploy
      env:
        CD: true
        TOKEN: ${{ secrets.TOKEN }}
